# Generated by Django 4.2.5 on 2023-10-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='users',
            new_name='user',
        ),
    ]
